# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request_target:
    types: [ assigned, opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Connect to PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql db: 'postgres'
        postgresql user: 'myuser'
        postgresql password: 'mypassword'
    - name: checks
      run: java -version && pwd && ls -al
    - name: Maven run
      run: mvn clean install
    - name: MAVEN BUILD
      run: mvn package
    # - name: Test with Maven
    #   run: mvn --batch-mode --update-snapshots verify
      env:
        ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
