name: Main Branch PR Workflow

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Java-Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Connect to PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'postgres'
          postgresql user: 'myuser'
          postgresql password: 'mypassword'
      - name: Build with Maven
        working-directory: Assignment03
        run: mvn clean install
      - name: Running test cases
        working-directory: Assignment033
        run: mvn test -Dtest=”CloudAssignment03ApplicationTests”
