name: Main Branch PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Java-Build-on-pull
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Connect to PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'postgres'
          postgresql user: 'myuser'
          postgresql password: 'mypassword'
      - name: Build with Maven
        working-directory: CloudAssignment03
        run: mvn clean install
      - name: Running test cases
        working-directory: CloudAssignment03
        run: mvn test -Dtest=HealthCheckIntegrationTest

      - name: Building Jar file
        working-directory: CloudAssignment03
        run: mvn package -Dmaven.test.skip=true

      - name: Checking AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Installing packer provisioners
        working-directory: packer_tmp
        run: packer init aws-debian.pkr.hcl

      - name: Formatting packer
        working-directory: packer_tmp
        run: packer fmt -check aws-debian.pkr.hcl

      - name: Running Packer template validation
        working-directory: packer_tmp
        run: packer validate --var-file="variables.auto.pkrvar.hcl" aws-debian.pkr.hcl



